name: My training theme
description: 'My custom theme for trainings'
type: theme
base theme: olivero
logo: images/mattermost.png
regions:
  header: Header
  primary_menu: Primary menu
  secondary_menu: Secondary menu
  hero: Hero (full width)
  highlighted: Highlighted
  breadcrumb: Breadcrumb
  social: Social Bar
  content_above: Content Above
  content: Content
  sidebar: Sidebar
  content_below: Content Below
  footer_top: Footer Top
  footer_bottom: Footer Bottom
libraries:
  - training_theme/global-styling
core_version_requirement: ^10
